swagger: "2.0"
info:
  version: "1.0.0"
  title: Freshworks
  description: Freshworks microservice
  license:
    name: UNLICENSED
basePath: /proxy
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      x-swagger-router-controller: hello
      description: Say hello.
      operationId: get
      parameters:
      - name: name
        in: query
        description: The person to say hello to.
        required: false
        type: string
      responses:
        "200":
          description: A hello message.
          schema:
            $ref: '#/definitions/HelloMessage'
        default:
          description: Error payload.
          schema:
            $ref: '#/definitions/ErrorMessage'
  /ping:
    get:
      x-swagger-router-controller: health-check
      description: Health check endpoint.
      operationId: get
      responses:
        "200":
          description: This service is healthy.
          schema:
            $ref: '#/definitions/PingResponse'
        default:
          description: Error payload.
          schema:
            $ref: '#/definitions/ErrorMessage'
definitions:
  ErrorMessage:
    type: object
    required:
      - message
    properties:
      message:
        type: string
  HelloMessage:
    type: object
    required:
      - message
    properties:
      message:
        type: string
  PingResponse:
    type: object
    required:
      - pong
    properties:
      pong:
        type: boolean
